### PR TITLE
PR for homepage of the restaurant

### PR DESCRIPTION
**Pull request by smcommits**
# Description

In this PR, I have implemented a simple dynamic homepage for a restaurant. The goal  was to use DOM manipulation in Javascript to dynamically generate all the HTML content. I have also used Javascript to create tabbed menu to navigate between menu and contact sections of the page. 

## Page Contents 
- Navigation Bar
- Hero Section
- About Section
- Tab Menu

## Javascript
I have used the ES6 version of Javascript. I have divided the code into multiples modules and used import and export statement to share the code. 

## Technologies Used
- Webpack for bundling the code 
- NPM for dependencies and script handling
- ESLINT for lining Javascript
- Sylelint for lining CSS

### CODE REVIEW

**Review by oloomoses — CHANGES_REQUESTED** [review]
# Status: Changes Required
**Hell @smcommits, great job especially with the pull request. :muscle: 
Below are some of the changes to be made before the project can be approved :point_down:** 

- [x] In the navigation bar, I should be able to switch between home and about. When 
a tab is clicked the content is replaced ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/tab_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page))
- [x] I suggest that you move that `Menu` and `Contact` into the main navigation bar.
- [x] You have some very important information in the pull request that should be added in the readme file for example **Technologies Used** part

Kindly implement the above changes before submitting another code review.
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
## HAPPY CODING 
_Slack: Oloo Moses_

**Comment by smcommits** [comment]
@oloomoses Thank you so much for the feedback. I have implemented the following changes:
- Moved the tabbed navbar to the top
- Add essential information in README

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @smcommits, congratulations on this project :muscle: The technologies used have been included in the README file as pointed out by the previous TSE :slightly_smiling_face: The navigation have also been fixed :smile: Awesome :fireworks: However, there is one important missing requirements I would like us to address, kindly check the comments below:
- The following should be added as a devDependencies
  - Webpack
  - Webpack-cli
  - Webpack-dev-server
fc

Once this is fixed, kindly submit another code review request :smile: 
_Hapy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
